### ISSUE TITLE
Why upload node_modules on /practiceWeb/trackerApp/mern-exercise-tracker folder

### ISSUE THREAD

**Issue by yogathanh99** [nguyenhaison1999/studyCode#3]
I think you should delete on .gitignore by adding node_modules/ instead use /node_modules

**Comment by nguyenhaison1999** [comment]
Ah, there are two different node_modules folders. Forgot to remove them all.
![image](https://user-images.githubusercontent.com/51308186/89423831-30474c80-d761-11ea-956b-7f3c3c07fde1.png)
Thanks man.

**Comment by yogathanh99** [comment]
Now, it's ok
